### ISSUE TITLE
Add support for retrieval of IMDS from IPv6 Endpoint

### ISSUE THREAD

**Issue by thimslugga** [aws/aws-ec2-imdsv2-get#4]
Add support for retrieving IMDS via IPv6 endpoint

>If you are retrieving instance metadata for EC2 instances over the IPv6 address, ensure that you enable and use the IPv6 address instead: fd00:ec2::254. The IPv6 address of the IMDS is compatible with IMDSv2 commands. The IPv6 address is only accessible on [Instances built on the Nitro System](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances).

- https://aws.amazon.com/about-aws/whats-new/2021/08/Ipv6-amazon-ec2-metadata-time-sync-vpc-dns/
- https://aws.amazon.com/about-aws/whats-new/2021/08/Ipv6-amazon-ec2-metadata-time-sync-vpc-dns/

Current:

```
..
const IMDS_URL: &str = "169.254.169.254:80";
..
```

**Comment by Likkrid** [comment]
Submitted the following [PR](https://github.com/aws/aws-ec2-imdsv2-get/pull/6)

**Comment by jmt-lab** [comment]
PR is merged and I've tagged a release and will reach out to colin to get the port updated
